version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - curl -sSL https://raw.githubusercontent.com/threatrix/distribution/master/threatagent-docker.sh | sh && docker run --env-file=host.env --name threatrix-threat-agent -v $(pwd):/app threatrix/threat-agent --oid=$HOST_THREATRIX_OID --eid=$HOST_THREATRIX_EID --api-key=$HOST_THREATRIX_API_KEY ./
      #- docker run --env-file=host.env --name threatrix-threat-agent -v $(pwd):/app threatrix/threat-agent ./
      #- mvn package
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
